fileshare/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),    
    path('g_cloud/', include('g_cloud.urls', namespace='g_cloud')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static('/templates/', document_root=settings.PROJECT_DIR + '/templates/')

#print(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

g_cloud/urls.py
from django.urls import path
from . import views
from django.conf import settings 
from django.conf.urls.static import static 

app_name = 'cloud'

urlpatterns = [
    path('g_cloud/', views.index, name='index'),
    path('folder_list1/<str:file_name>/<str:folder>/', views.download),
    path('files_list2/<str:file_name>/<str:folder>/', views.download),
    path('files_list/<str:folder>/', views.folder_list, name='folder_list'),
    path('files_list/', views.files_list, name='files_list'),
    path('files_list4/', views.files_list, name='files_list'),
    path('files_list5/<str:file_name>/', views.download),
    path('<str:file_name>/str:path>/', views.download, name='download'),
    path('files_list6/<str:file_name>/<str:folder>/', views.download, name='download'),
    path('photo_save/', views.photo_save, name='save'),
    path('', views.photo_save, name='save'),
    path('file_upload/', views.file_upload, name='file_upload'),
    path('', views.file_upload, name='file_upload'),
    path('multi_file/', views.multi_file, name='multi_file'),
    path('', views.multi_file, name='multi_file'),
    path('dir_upload/', views.dir_upload, name='dir_upload'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

g_cloud/models.py
from django.db import models
#from django.conf import settings
#from django.core.files.storage import FileSystemStorage
from django import forms
###
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import os

# Create your models here.

class Image(models.Model):
    photo = models.ImageField(upload_to = 'images/', default = 'media/images/users.jpg')
    
    def get_photo_url(self):
        if self.photo and hasattr(self.photo, 'url'):
            return self.photo.url
        else:
            return "images/users.png"


class Document(models.Model):
    upload = models.FileField(upload_to='uploads/', default = 'media/images/users.jpg')
    
    def get_document_url(self):
        if self.upload and hasattr(self.upload, 'url'):
            return self.upload.url
        else:
            return "files/users.png"


class MultiFile(models.Model):
    uploads = models.FileField(upload_to='files/', default = 'media/images/users.jpg')
    
    

class DirUpload(models.Model):
    directory = models.FileField(upload_to='temp/', default = 'media/images/users.jpg')
    
    
class Title(models.Model):
    title =  models.CharField(max_length=30)
    doc = models.ForeignKey(DirUpload, on_delete=models.CASCADE, null=True, blank=True)

g_cloud/forms.py
from django import forms
from django.forms import ClearableFileInput
from .models import Image, Document, MultiFile, DirUpload, Title

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['photo']
        photo = forms.ImageField()


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('upload',)


class MultiFileForm(forms.ModelForm):
    class Meta:
        model = MultiFile
        fields = ['uploads',]
        widgets = {
            'uploads': ClearableFileInput(attrs={'multiple': True}),
        }
        
        
class FileFieldForm(forms.Form):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs=
        {'multiple': True, 'webkitdirectory': True, 'directory': True}))
        
        
class DirForm(forms.ModelForm):
    class Meta:
        model = DirUpload
        fields = ('directory',)
        
        
class TitleForm(forms.ModelForm):
    class Meta:
        model = Title
        fields = ('title',)
        

g_cloud/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .forms import ImageForm, DocumentForm, MultiFileForm, DirForm, TitleForm
from .models import *
from django.template import RequestContext
import os
from wsgiref.util import FileWrapper
import mimetypes
import urllib 
from django.http import HttpResponse
from django.utils.encoding import smart_str
from PIL import Image
import shutil

# Create your views here.

def photo_save(request):
    if request.method != 'POST':
        # No data submitted create a blank form.
        form  = ImageForm()
    else:
        #POST data submitted; process data.
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            #m = Image.objects.get(pk=course_id)
            #m.model_pic = form.cleaned_data['image']
            #m.save()
            new_image = form.save(commit=False)
            #new_image.id = 1
            new_image.save()
            context = {'form': form}
            return render(request, 'g_cloud/new_photo.html', context)
    
    context = {'form': form}
    return render(request, 'g_cloud/new_photo.html', context)
    
    
    
     
def file_upload(request):
    if request.method != 'POST':
        form = DocumentForm()
    else:
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            new_file = form.save(commit=False)
            new_file.save()
            context = {'form': form}
            return render(request, 'g_cloud/new_file.html', context)
    
    context = {'form': form}
    return render(request, 'g_cloud/new_file.html', context)
    
    
    
###
def multi_file(request):
    if request.method != 'POST':
        form = MultiFileForm()
    else:
        form = MultiFileForm(request.POST, request.FILES)
        files = request.FILES.getlist('uploads')
        #print(files)
        if form.is_valid():
             for f in files:
                  file_instance = MultiFile(uploads=f)
                  print(f)
                  file_instance.save()
                                
    context = {'form': form}
    return render(request, 'g_cloud/multi_file.html', context)
    
    
def files_list(request):
    folders = []
    files = []
    context = {'total_files':os.listdir(settings.MEDIA_ROOT),'path':settings.MEDIA_ROOT}
    print(os.listdir(settings.MEDIA_ROOT))
    print(settings.MEDIA_ROOT)
    for i in os.listdir(settings.MEDIA_ROOT):
        path=settings.MEDIA_ROOT +'/'+ i
        if os.path.isdir(path):  
            c = {str(i): os.listdir(path)}
            folders.append(c)
        else:
            files.append(i)
            #print(c)
    context = {'folders' : folders, 'files' : files}
    return render(request, 'g_cloud/files_list.html', context)
    
    
    
def download(request, file_name, folder='0'):
    if folder != '0':
        file_path = settings.MEDIA_ROOT + folder + '/' + file_name
    else:
        file_path = settings.MEDIA_ROOT + file_name
    filename, file_extension = os.path.splitext(file_path)
    print(type(file_extension))
    if file_path.lower().endswith(('.png', '.jpg', '.jpeg')):
        print(1)
        fl = Image.open(file_path)
        
    else:
        print(2) 
        fl = open(file_path, "r")
    file_wrapper = FileWrapper(file_path, 'rb')
    file_mimetype, _ = mimetypes.guess_type(file_path)
    #print(file_mimetype)
    response = HttpResponse(fl, content_type=file_mimetype )
    response['X-Sendfile'] = file_path
    response['Content-Length'] = os.stat(file_path).st_size
    response['Content-Disposition'] = 'attachment; filename=%s/' % smart_str(file_name) 
    return response
    
    
def folder_list(request, folder, path=settings.MEDIA_ROOT):
    path=settings.MEDIA_ROOT +''+ folder  
    context = {'folder':os.listdir(path), 'path' : path, 'dir' : folder}
    print(os.listdir(path))
    print(folder)
    return render(request, 'g_cloud/folder_list.html', context)
    
    
def dir_upload(request):
    if request.method != 'POST':
         fl = DirForm()
         ttl = TitleForm()
    else:
        fl = DirForm(request.POST, request.FILES)
        ttl = TitleForm(data=request.POST)
        if fl.is_valid():
            for afile in request.FILES.getlist('directory'):          
                title = ttl.save(commit=False)
                new_file = DirUpload(directory = afile)
                new_file.save()
                title.doc = new_file                          
                title.save()
                #rename(title.title)
            rename(title.title)
            print(title.title)
    #rename(title.title)
    context = {'fl' : fl, 'ttl' : ttl}
    return render(request, 'g_cloud/dir_upload.html', context)

g_cloud/templates/g_cloud/dir_upload.html
{% block content %}
  <p> ....... </p>
 <form method="post" enctype="multipart/form-data">
   {% csrf_token %}
   {{ ttl.as_p }}
   
   <input type="file" name="directory" multiple = "true" webkitdirectory="true" directory = "true"/>
   <button type="submit">Upload</button>
</form>

{% endblock content %}

g_cloud/templates/g_cloud/files_list.html
<table border="1" colspan="2" width="100%">
   <tr>
     <th width="60%">File</td>
     <th width="40%">Download</td> 
   </tr>
 {% for file in files %}
   <tr>
     <td width="60%">{{file}}</td>
     <td width="40%" align="center"><a href="{% url "g_cloud:download" file_name=file %}"> {{file}}  </td></a>
   </tr>
 {% endfor %}  
</table>


<table border="1" colspan="2" width="100%">
   <tr>
     <th width="60%">Folder</td>
     <th width="40%">path</td> 
   </tr>
 {% for folder in folders %}
  {% for f in folder %}
     <tr>
      <td width="60%">{{f}}</td>
      <td width="40%" align="center"><a href="{% url "g_cloud:folder_list" f  %}"> {{f}} </td></a>
    </tr>
 {% endfor %}  
  {% endfor %}
   
</table>

g_cloud/templates/g_cloud/folder_list.html
<table border="1" colspan="2" width="100%">
   <tr>
     <th width="60%">File</td>
     <th width="40%">Download</td> 
   </tr>
 {% for f in folder %}
   <tr>
     <td width="60%">{{f}}</td>
     <td width="40%" align="center"><a href="{% url "g_cloud:download" f dir %}"> {{f}} </td></a>
     
   </tr>
 {% endfor %}
 </table>

g_cloud/templates/g_cloud/folder_upload.html
<input type="hidden" name="dir_name" id="id_dir_name">
<input type="file" name="file" onchange="selectFolder(event)" webkitdirectory="" multiple="" required="" directory="" id="id_file">

g_cloud/templates/g_cloud/multi_file.html
{% load crispy_forms_tags %}
{% block content %}
    <h1>Upload PDF</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Upload Resumes</button>
    </form> 
{% endblock content %}

g_cloud/templates/g_cloud/new_file.html
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }} 
    <button type="submit">Create</button>
  </form>
{% endblock content %}

g_cloud/templates/g_cloud/new_photo.html
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }} 
    <button type="submit">Create</button>
  </form>
{% endblock content %}